run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 150
    statements: 80

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosimple
    - importas
    - ineffassign
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - staticcheck
    - thelper
    - typecheck
    - unparam
    - unused
    - whitespace
