name: code daemon test

on:
  push:
    branches:
      - '**'

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.22

      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.22

      - name: Check out code
        uses: actions/checkout@v3

      - name: Unit tests
        run: go test -v -count=1 -race -timeout=1m ./tests/

      - name: Optimization tests
        run: go test -v -count=1 -timeout=1m -tags bench ./...
        if: env.GITHUB_BRANCH == 'hw10_program_optimization'
        